baseURL = 'https://ntsmith7.github.io/'
languageCode = 'en-us'
title = "Nicholas Smith"
theme = 'ananke'

# Add this param to ensure your custom CSS loads
[params]
  custom_css = ["css/portfolio.css"]